### ISSUE TITLE
Still Here

### ISSUE THREAD

**Issue by Programazing** [genericallyloud/codehike#35]
If this project ever gets revived I'd be willing to help out.

**Comment by Programazing** [comment]
![So long and thanks for all the fish](https://lh5.googleusercontent.com/-OEiKEsadyWY/U4EKibACGOI/AAAAAAAAErc/3AMyNQEHzTw/s640/blogger-image-483407795.jpg)

**Comment by genericallyloud** [comment]
Feel free to fork and run with the idea.
