### ISSUE TITLE
User Story: How to Get Started

### ISSUE THREAD

**Issue by Programazing** [genericallyloud/codehike#7]
The user starts out on the homepage and at the top, on a simple menu bar (like StackOverflow or GitHub), clicks something like "Go hiking" or "Hit the Trail."

The user lands on a central page that maybe we'd call "Camp" (Base Camp sounded too copyrighted) or something in line with our hiking theme. There they would have all of their Trails laid out before them so they could easily be able to pick something. I like the idea of the paths being in large boxes with some information about that trail inside of it. Something similar to Codecademy's catalog.

![codecademy](https://cloud.githubusercontent.com/assets/11393826/14194057/3b9bf7c0-f778-11e5-8164-8ec225efa8ca.png)

If the user has not started a trail yet there would be a blank box that says something like "Get Started!" that would take the user to a simple walkthrough tutorial. I like videos but I like the idea of walking the user through setting up their first project. There would also be an option in that box that says "No Thanks" to let them just wing it.

That's how I envision someone getting started or just getting to their Trails.

**Comment by genericallyloud** [comment]
One idea would be that every new user account has a trail for getting started with CodeHike. Sort of a way of having them use the tool to learn the tool.

**Comment by genericallyloud** [comment]
So there's a couple of elements in there that I would like to tease out. When you land on CodeHike.org, what do you see? If you don't have an account or are not logged in, you're going to get something different than if you _are_ logged in.

If you are _not_ logged in, then we're basically talking about the home page experience. We would want it to both demonstrate what CodeHike is, why you should want to sign up, what some good trails/hikes are, and then also have a good callout for signing up.

If you _are_ logged in, then we've got a couple of options for what exactly we want to display for them. Should it drop them right into their current trail/hike? Should it show their activity and the activity of other hikers they might know. Should it show other hikes/trails they might be interested in? I think all of those things should be available to them, so we can start brainstorming on all of that, but part of the question should really be about what the focus is. If we drop them right into their current trail, there's no distractions and they can get right to work. On the other hand, showing activity, other trails, etc. first before they choose to dig into their trail places a bigger emphasis on the whole CodeHike community, what other people are doing, who they might want to get connected with, what they might want to do next etc.

**Comment by Programazing** [comment]
To be honest I skipped the Main page because I was just focused on this specific concept of "what happens when I click Hit the Trails?" or whatever we call it.

Do you want to explore the idea of the homepage (logged in and out) here or in a new issue?

**Comment by genericallyloud** [comment]
Probably a new issue. The biggest thing I'd like to do is getting enough of an idea about what the main entities are and how they relate so we can start having a working prototype. Some of the questions coming up in discussion now are more related to usability aspects like discovery of new trails or confusion on how to use them. I think those are worthwhile questions, but are probably better figured out through prototyping.

I think homepage logged in and homepage logged out should probably each be separate issues.
